const mydata ={
    new_arrivals:[
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-20-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2017/08/product-13-600x600.jpg",
            name:'Flower Glass Vase',
            price:259.00,
            id:1,
            desc:"A vase is an open container. It can be made from a number of materials, such as ceramics, glass, non-rusting metals, such as aluminium, brass, bronze, or stainless steel",
        },   
          
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-1-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-1.1-600x600.jpg",                
            name:'Clockwatcher',
            price:571.00,
            id:2,
            desc:"A clock is a machine in which a device that performs regular movements in equal intervals of time is linked to a counting mechanism that records the number of movements. All clocks, of whatever form, are made on this principle",
        }, 
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-2-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-14-600x600.jpg",
            name:'Hanmade Pillow',
            price:210.00,
            id:3,
            desc:"Especially on chairs for sitting or leaning on) that can be moved around and used in different places: A circular blue couch with a few throw pillows stood empty.",
        },  
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-3-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-14-600x600.jpg",
            name:'Fauteuil Bulle',
            price:30.99,
            id:4,
            desc:"Both horizontal and vertical adjustments are recommended. Properly designed armrests help support upper arms, back and neck.",
        },  
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-4-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-4-600x600.jpg",
            name:'Fazen Mikam',
            price:20.00,
            id:5,
            desc:" Sofa, sectional, or love seat in the body to describe your item in greater detail.",
        },  
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-5-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-10-600x600.jpg",
            name:'Chaise Pied Eifel',
            price:815.00,
            id:6,
            desc:"Both horizontal and vertical adjustments are recommended. Properly designed armrests help support upper arms, back and neck.",
        },  
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-6-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-16-600x600.jpg",
            name:'Bouquet Flower Vase',
            price:214.20,
            id:7,
            desc:"A vase is an open container. It can be made from a number of materials, such as ceramics, glass, non-rusting metals, such as aluminium, brass, bronze, or stainless steel",
        },  
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-7-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-15-600x600.jpg",
            name:'Ford Bouquet Cups',
            price:205.00,
            id:8,
            desc:"Usually having a handle and used chiefly as a receptable from which to drink tea, soup, etc. the bowllike part of a goblet or the like. a cup with its contents. the quantity contained in a cup.",
        },  
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-8-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-19-600x600.jpg",
            name:'Fritz Hansen Objects',
            price:287.00,
            id:9,
            desc:" Bright, flashing lightning lighting up the sky like fireworks; banging, crashing thunder roaring furiously, sizzling, electrifying lightning zipping across the night sky.",
        },  
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-9-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-19-600x600.jpg",
            name:'Lichtarena Lights',
            price:30.50,
            id:10,
            desc:" Bright, flashing lightning lighting up the sky like fireworks; banging, crashing thunder roaring furiously, sizzling, electrifying lightning zipping across the night sky.",
        },
        {
            shown_img:"https://images.unsplash.com/photo-1540574163026-643ea20ade25?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8c29mYXxlbnwwfDB8MHx8&auto=format&fit=crop&w=400&q=60",
            hiden_img:"https://images.unsplash.com/photo-1578500494198-246f612d3b3d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTZ8fHNvZmF8ZW58MHwwfDB8fA%3D%3D&auto=format&fit=crop&w=400&q=60",
            name:'Fazen Mikam',
            price:28.00,
            id:11,
            desc:" Sofa, sectional, or love seat in the body to describe your item in greater detail.",
        }, 
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-1-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-1.1-600x600.jpg",                
            name:'Clockwatcher',
            price:571.00,
            id:12,
            desc:"A clock is a machine in which a device that performs regular movements in equal intervals of time is linked to a counting mechanism that records the number of movements. All clocks, of whatever form, are made on this principle",
        },
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-7-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-15-600x600.jpg",
            name:'Ford Bouquet Cups',
            price:205.00,
            id:13,
            desc:"Usually having a handle and used chiefly as a receptable from which to drink tea, soup, etc. the bowllike part of a goblet or the like. a cup with its contents. the quantity contained in a cup.",
        },  
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-5-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-10-600x600.jpg",
            name:'Chaise Pied Eifel',
            price:815.00,
            id:14,
            desc:"Both horizontal and vertical adjustments are recommended. Properly designed armrests help support upper arms, back and neck.",
        },  
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-9-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-19-600x600.jpg",
            name:'Lichtarena Lights',
            price:30.50,
            id:15,
            desc:" Bright, flashing lightning lighting up the sky like fireworks; banging, crashing thunder roaring furiously, sizzling, electrifying lightning zipping across the night sky.",
        },
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-8-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-19-600x600.jpg",
            name:'Fritz Hansen Objects',
            price:287.00,
            id:16,
            desc:" Bright, flashing lightning lighting up the sky like fireworks; banging, crashing thunder roaring furiously, sizzling, electrifying lightning zipping across the night sky.",
        }, 
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-6-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-16-600x600.jpg",
            name:'Bouquet Flower Vase',
            price:214.20,
            id:17,
            desc:"A vase is an open container. It can be made from a number of materials, such as ceramics, glass, non-rusting metals, such as aluminium, brass, bronze, or stainless steel",
        },  
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-20-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2017/08/product-13-600x600.jpg",
            name:'Flower Glass Vase',
            price:259.00,
            id:18,
            desc:"A vase is an open container. It can be made from a number of materials, such as ceramics, glass, non-rusting metals, such as aluminium, brass, bronze, or stainless steel",
        },
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-3-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-14-600x600.jpg",
            name:'Fauteuil Bulle',
            price:30.99,
            id:19,
            desc:"Both horizontal and vertical adjustments are recommended. Properly designed armrests help support upper arms, back and neck.",
        },  
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-6-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-16-600x600.jpg",
            name:'Bouquet Flower Vase',
            price:214.20,
            id:20,
            desc:"A vase is an open container. It can be made from a number of materials, such as ceramics, glass, non-rusting metals, such as aluminium, brass, bronze, or stainless steel",
        },
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-3-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-14-600x600.jpg",
            name:'Fauteuil Bulle',
            price:30.99,
            id:21,
            desc:"Both horizontal and vertical adjustments are recommended. Properly designed armrests help support upper arms, back and neck.",
        },  
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-20-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2017/08/product-13-600x600.jpg",
            name:'Flower Glass Vase',
            price:259.00,
            id:22,
            desc:"A vase is an open container. It can be made from a number of materials, such as ceramics, glass, non-rusting metals, such as aluminium, brass, bronze, or stainless steel",
        },
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-6-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-16-600x600.jpg",
            name:'Bouquet Flower Vase',
            price:214.20,
            id:23,
            desc:"A vase is an open container. It can be made from a number of materials, such as ceramics, glass, non-rusting metals, such as aluminium, brass, bronze, or stainless steel",
        }, 
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-8-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-19-600x600.jpg",
            name:'Fritz Hansen Objects',
            price:287.00,
            id:24,
            desc:" Bright, flashing lightning lighting up the sky like fireworks; banging, crashing thunder roaring furiously, sizzling, electrifying lightning zipping across the night sky.",
        },
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-9-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-19-600x600.jpg",
            name:'Lichtarena Lights',
            price:30.50,
            id:25,
            desc:" Bright, flashing lightning lighting up the sky like fireworks; banging, crashing thunder roaring furiously, sizzling, electrifying lightning zipping across the night sky.",
        },
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-5-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-10-600x600.jpg",
            name:'Chaise Pied Eifel',
            price:815.00,
            id:26,
            desc:"Both horizontal and vertical adjustments are recommended. Properly designed armrests help support upper arms, back and neck.",
        },
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-7-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-15-600x600.jpg",
            name:'Ford Bouquet Cups',
            price:205.00,
            id:27,
            desc:"Usually having a handle and used chiefly as a receptable from which to drink tea, soup, etc. the bowllike part of a goblet or the like. a cup with its contents. the quantity contained in a cup.",
        }, 
        {
            shown_img:"https://cdn.lorem.space/images/furniture/.cache/640x480/paul-weaver-nWidMEQsnAQ-unsplash.jpg",
            hiden_img:"https://cdn.lorem.space/images/furniture/.cache/640x480/paul-weaver-nWidMEQsnAQ-unsplash.jpg",
            name:'Fazen Mikam',
            price:32.00,
            id:28,
            desc:" Sofa, sectional, or love seat in the body to describe your item in greater detail.",
        }, 
        {
            shown_img:"https://images.unsplash.com/photo-1462530260150-162092dbf011?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=786&q=80",
            hiden_img:"https://images.unsplash.com/photo-1468174482686-1047396f13b3?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDR8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=400&q=60",
            name:'Lichtarena Lights',
            price:31.50,
            id:29,
            desc:" Bright, flashing lightning lighting up the sky like fireworks; banging, crashing thunder roaring furiously, sizzling, electrifying lightning zipping across the night sky.",
        },
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-8-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-19-600x600.jpg",
            name:'Fritz Hansen Objects',
            price:287.00,
            id:30,
            desc:" Bright, flashing lightning lighting up the sky like fireworks; banging, crashing thunder roaring furiously, sizzling, electrifying lightning zipping across the night sky.",
        }, 
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-7-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-15-600x600.jpg",
            name:'Ford Bouquet Cups',
            price:205.00,
            id:31,
            desc:"Usually having a handle and used chiefly as a receptable from which to drink tea, soup, etc. the bowllike part of a goblet or the like. a cup with its contents. the quantity contained in a cup.",
        }, 
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-6-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-16-600x600.jpg",
            name:'Bouquet Flower Vase',
            price:214.20,
            id:32,
            desc:"A vase is an open container. It can be made from a number of materials, such as ceramics, glass, non-rusting metals, such as aluminium, brass, bronze, or stainless steel",
        },  
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-5-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-10-600x600.jpg",
            name:'Chaise Pied Eifel',
            price:815.00,
            id:33,
            desc:"Both horizontal and vertical adjustments are recommended. Properly designed armrests help support upper arms, back and neck.",
        },  
        {
            shown_img:"https://cdn.lorem.space/images/furniture/.cache/640x480/jean-philippe-delberghe-feijc-nqWKM-unsplash.jpg",
            hiden_img:"https://images.unsplash.com/photo-1506332088442-9e0024864f5d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTd8fGNoYWlyfGVufDB8MHwwfHw%3D&auto=format&fit=crop&w=400&q=60",
            // hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-4-600x600.jpg",
            name:'Fazen Mikam',
            price:14.00,
            id:34,
            desc:" Sofa, sectional, or love seat in the body to describe your item in greater detail.",
        }, 
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-3-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-14-600x600.jpg",
            name:'Fauteuil Bulle',
            price:30.99,
            id:35,
            desc:"Both horizontal and vertical adjustments are recommended. Properly designed armrests help support upper arms, back and neck.",
        },  
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-2-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-14-600x600.jpg",
            name:'Hanmade Pillow',
            price:210.00,
            id:36,
            desc:"Especially on chairs for sitting or leaning on) that can be moved around and used in different places: A circular blue couch with a few throw pillows stood empty.",
        }, 
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-1-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-1.1-600x600.jpg",                
            name:'Clockwatcher',
            price:571.00,
            id:37,
            desc:"A clock is a machine in which a device that performs regular movements in equal intervals of time is linked to a counting mechanism that records the number of movements. All clocks, of whatever form, are made on this principle",
        }, 
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-20-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2017/08/product-13-600x600.jpg",
            name:'Flower Glass Vase',
            price:259.00,
            id:38,
            desc:"A vase is an open container. It can be made from a number of materials, such as ceramics, glass, non-rusting metals, such as aluminium, brass, bronze, or stainless steel",
        },   
        {
            // shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-4-600x600.jpg",
            // shown_img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQOtO0N1ZQij2Bq_jKCmu8y5xt2e6kbPeG9Q&usqp=CAU",
            shown_img:"https://i.pinimg.com/236x/94/0e/cb/940ecb862d684587726ef15db97b8e8b.jpg",
            hiden_img:"https://i.pinimg.com/236x/77/cc/14/77cc147b99cb219e52d59e84d255aa37.jpg",
            name:'Fazen Mikam',
            price:24.00,
            id:39,
            desc:" Sofa, sectional, or love seat in the body to describe your item in greater detail.",
        }, 
        {
            shown_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-7-600x600.jpg",
            hiden_img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2016/04/product-15-600x600.jpg",
            name:'Ford Bouquet Cups',
            price:205.00,
            id:40,
            desc:"Usually having a handle and used chiefly as a receptable from which to drink tea, soup, etc. the bowllike part of a goblet or the like. a cup with its contents. the quantity contained in a cup.",
        }, 
    ],
    blogprod:[
        {
            img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2017/04/blog-1.jpg",
            headtext:"WHITNEY MUSEUM OF AMERICAN ART",
            desc:"This exhibition brings together paintings by five artists—Nina Chanel Abney, Mathew Cerletty, Jamian Juliano-Villani, Caitlin Keogh, and Orion Martin. Highlighting an engagement with representation among some emerging artists, the works in this group conjure a sense of space that is dimensionless and airless, like the illusionistic scenery flats used on stage and movie sets.Each of these artists fills their compositions with objects, bodies and places that are based on reality, yet are exaggerated, recontextualized, simplified or flattened. The individual works are imbued with both the uncertainty of our sociopolitical moment as well as the seductive quality of consumerism and physical attraction. The paintings in Flatlandsinvite the viewer to reflect on this ever-present polarity and ambivalence of contemporary life.Flatlands is organized by assistant curators Laura Phipps and Elisabeth Sherman.The exhibition will be on view through April 17, 2016 in the John R. Eckel, Jr. Foundation Gallery, on the Museum’s first floor, which is accessible to the public free-of-charge.",
            dateMonth:"April",
            dateDay:19,
            dateYear:2017,
            author:"Jamie",
            comment:1,
            id:1,
        },
        {
            img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2017/04/blog-10.jpg",
            headtext:"POST FORMAT GALLERY",
            desc:"Aliquam vitae fermentum ante. Nam dapibus odio ut aliquam dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent placerat elementum diam ac sagittis. Phasellus gravida sem elit, at porttitor felis gravida a. Curabitur sed blandit diam.",
            dateMonth:"April",
            dateDay:17,
            dateYear:2017,
            author:"Jamie",
            comment:0,
            id:2,
        },
        {
            img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2017/04/blog-2.jpg",
            headtext:"POST FORMAT AUDIO",
            desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel massa eget ante tincidunt vestibulum. Aenean vel metus magna. Mauris nec velit tortor, quis euismod lectus. Nulla et arcu libero. Cras pretium, ipsum quis adipiscing condimentum, turpis urna lobortis neque, nec dignissim ipsum mauris sed nunc.",
            dateMonth:"April",
            dateDay:17,
            dateYear:2017,
            author:"Jamie",
            comment:1,
            id:3,
        },
        {
            img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2017/04/blog-4.jpg",
            headtext:"POST FORMAT VIDEO",
            desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel massa eget ante tincidunt vestibulum. Aenean vel metus magna. Mauris nec velit tortor, quis euismod lectus. Nulla et arcu libero. Cras pretium, ipsum quis adipiscing condimentum, turpis urna lobortis neque, nec dignissim ipsum mauris sed nunc.",
            dateMonth:"April",
            dateDay:17,
            dateYear:2017,
            author:"Jamie",
            comment:2,
            id:4,
        },
        {
            img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2017/04/blog-5.jpg",
            headtext:"POST FORMAT QUOTE",
            desc:"Quisque tempor urna sed metus lobortis, vitae posuere lacus varius. Curabitur justo velit, laoreet vel tristique quis, aliquam nec nisl. Vestibulum vel arcu nunc.",
            dateMonth:"April",
            dateDay:17,
            dateYear:2017,
            author:"Jamie",
            comment:1,
            id:5,
        },
        {
            img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2017/04/blog-6.jpg",
            headtext:"HOT TRENDING CLOTHING FOR WOMEN",
            desc:"Quisque tempor urna sed metus lobortis, vitae posuere lacus varius. Curabitur justo velit, laoreet vel tristique quis, aliquam nec nisl. Vestibulum vel arcu nunc.",
            dateMonth:"November",
            dateDay:13,
            dateYear:2016,
            author:"Jamie",
            comment:1,
            id:6,
        },
        {
            img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2017/04/blog-7.jpg",
            headtext:"DELENITI NAM PORRO QUISQUAM AB TEMPORIBUS",
            desc:"Quisque tempor urna sed metus lobortis, vitae posuere lacus varius. Curabitur justo velit, laoreet vel tristique quis, aliquam nec nisl. Vestibulum vel arcu nunc.",
            dateMonth:"November",
            dateDay:13,
            dateYear:2016,
            author:"Jamie",
            comment:1,
            id:7,
        },
        {
            img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2017/04/blog-8.jpg",
            headtext:"HOW TO MAKE YOUR FIRST 10 SALES",
            desc:"There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or ranrange domised words which don’t look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn’t anything on at embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this is the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. In The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.",
            dateMonth:"November",
            dateDay:13,
            dateYear:2016,
            author:"Jamie",
            comment:1,
            id:8,
        },
        {
            img:"https://wpbingosite.com/wordpress/oritina/wp-content/uploads/2017/04/blog-9.jpg",
            headtext:"5 WAYS TO IMPROVE ONLINE SECURITY",
            desc:"As a business owner, it’s important to take information security seriously – not only for your sake, but your customers’ too. Allowing sensitive data to fall into the wrong hands can cause serious trouble for your brand reputation, or worse.Today, we’re going to highlight some of the easiest and most effective ways you can protect your important accounts, online activity, and device data from prying eyes and malicious activity.Don’t worry – it’s easier than it sounds.",
            dateMonth:"November",
            dateDay:13,
            dateYear:2016,
            author:"Jamie",
            comment:1,
            id:9,
        },
    ]

    
}

export default mydata;